#!/usr/bin/with-contenv bash
# shellcheck shell=bash

PUID=${PUID:-<uid>}
PGID=${PGID:-<uid>}

groupmod -o -g "$PGID" <user>
usermod -o -u "$PUID" <user>

cat /etc/s6-overlay/s6-rc.d/init-adduser/branding

if [[ -f /donate.txt ]]; then
    echo '
To support the app dev(s) visit:'
    cat /donate.txt
fi
echo '
To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────'
echo "
User UID:    $(id -u <user>)
User GID:    $(id -g <user>)
───────────────────────────────────────
"

if [[ "$(uname -m)" == "armv7l" ]] || [[ "$(uname -m)" == "armhf" ]]; then
    echo '
╔═════════════════════════════════════════════════════╗
║                                                     ║
║      The 32-bit Arm version of this image will      ║
║       no longer be supported after 2023-07-01       ║
║                                                     ║
║          See: https://linuxserver.io/armhf          ║
║                  for more details                   ║
║                                                     ║
╚═════════════════════════════════════════════════════╝
'
fi

lsiown <user>:<user> /app
lsiown <user>:<user> /config
lsiown <user>:<user> /defaults
